default: &default
  adapter: sqlite3
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: freelance_camp_proposal_development

test:
  <<: *default
  database: freelance_camp_proposal_test

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: freelance_camp_proposal_production
  username: freelance_camp_proposal
  password: <%= ENV['FREELANCE_CAMP_PROPOSAL_DATABASE_PASSWORD'] %>
